RELAXATION_RESOURCES = [
    {
        "title": "Abuse",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/3917/0913/6697/NHS-Cumbria-Abuse.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/abuse-audio-transcript/",
    },
    {
        "title": "Alcohol and You",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/1617/0913/7944/NHS-Cumbria-AlcoholandYou.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/alcohol-and-you-audio-transcript/",
    },
    {
        "title": "Anxiety",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/7717/0913/9287/NHS-Cumbria-Anxiety.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/anxiety-audio-transcript/",
    },
    {
        "title": "Bereavement",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/7917/0913/7411/NHS-Cumbria-Bereavement.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/bereavement-audio-transcript/",
    },
    {
        "title": "Controlling Anger",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/6017/0913/7717/NHS-Cumbria-Controlling_Anger.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/controlling-anger-audio-transcript/",
    },
    {
        "title": "Depression and Low Mood",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/6817/2719/3906/NHS-Cumbria-Depressionand_LowMood.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/depression-and-low-mood-audio-transcript/",
    },
    {
        "title": "Depression and Low Mood – a Guide for Partners",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/2917/1576/1373/Clare_NHS_MP3_Depression_Guide_with_links_Final.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/depression-and-low-mood-a-guide-for-partners-audio-transcript/",
    },
    {
        "title": "Domestic Abuse",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/5617/0913/9662/NHS-Cumbria-DomesticAbuse.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/domestic-abuse-audio-transcript/",
    },
    {
        "title": "Eating Disorders",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/9317/0914/0017/NHS-Cumbria-EatingDisorders.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/eating-disorder-audio-transcript/",
    },
    {
        "title": "Food for Thought",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/8217/0930/4079/NHS-Cumbria-FoodForThought.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/food-for-thought-audio-transcript/",
    },
    {
        "title": "Health Anxiety",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/4117/0914/0771/NHS-Cumbria-HealthAnxiety.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/health-anxiety-audio-transcript/",
    },
    {
        "title": "Hearing Voices and Disturbing Beliefs",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/4317/0914/0883/NHS-Cumbria-HearingVoicesandDisturbingBeliefs.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/hearing-voices-and-disturbing-beliefs-audio-transcript/",
    },
    {
        "title": "Obsessions and Compulsions",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/3117/0914/1121/NHS-Cumbria-ObsessionsandCompulsions.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/obsessions-and-compulsions-audio-transcript/",
    },
    {
        "title": "Panic",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/7917/0930/4253/NHS-Cumbria-Panic.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/panic-audio-transcript/",
    },
    {
        "title": "Post Traumatic Stress",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/5117/0921/7898/NHS-Cumbria-PostTraumaticStress.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/post-traumatic-stress-audio-transcript/",
    },
    {
        "title": "Postnatal Depression",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/6017/0921/7658/NHS-Cumbria-PostnatalDepression.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/postnatal-depression-audio-transcript/",
    },
    {
        "title": "Self-Harm",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/7117/0921/7239/NHS-Cumbria-SelfHarm.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/self-harm-audio-transcript/",
    },
    {
        "title": "Social Anxiety",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/1917/0919/7678/NHS-Cumbria-SocialAnxiety.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/social-anxiety-audio-transcript/",
    },
    {
        "title": "Sleeping Problems",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/9517/0921/7066/NHS-Cumbria-SleepingProblems.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/sleeping-problems-audio-transcript/",
    },
    {
        "title": "Stress",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/7317/0919/7406/NHS-Cumbria-Stress.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/stress-audio-transcript/",
    },
    {
        "title": "Anxiety for People in Prison",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/3417/0913/7547/NHS-Cumbria-AnxietyPrison.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/anxiety-for-people-in-prison-audio-transcript/",
    },
    {
        "title": "Depression and Low Mood for People in Prison",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/8417/0913/9510/NHS-Cumbria-DepressionLowMoodPrison.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/depression-and-low-mood-for-people-in-prison-audio-transcript/",
    },
    {
        "title": "Post Traumatic Stress for People in Prison",
        "audio_file": "https://selfhelp.cntw.nhs.uk/application/files/5317/0921/8077/NHS-Cumbria-Post_TraumaticStressPrison.mp3",
        "transcript": "https://www.cntw.nhs.uk/home/accessible-information/audio/self-help-guides-audio-transcripts/post-traumatic-stress-for-people-in-prison-audio-transcript/",
    },
]


SEARCH_OPTIONS = [
    "Abuse",
    "Alcohol",
    "Anxiety",
    "Anger",
    "Bereavement",
    "Depression",
    "Eating Disorders",
    "Health Anxiety",
    "Hearing Voices",
    "Obsessions and Compulsions",
    "Panic",
    "Post-Traumatic Stress",
    "Postnatal Depression",
    "Self-Harm",
    "Sleeping Problems",
    "Social Anxiety",
    "Stress",
    "Work and Tension",
    "Substance Misuse",
]


MOODS = {
    "6": {
        "int": 6,
        "color": "Dark green",
        "description": "Happy \U0001f600",
        "ansi": "\033[32m",
    },
    "5": {
        "int": 5,
        "color": "Green",
        "description": "Content \U0001f642",
        "ansi": "\033[92m",
    },
    "4": {
        "int": 4,
        "color": "Yellow",
        "description": "Neutral \U0001f610",
        "ansi": "\033[93m",
    },
    "3": {
        "int": 3,
        "color": "Orange",
        "description": "Low \U0001f641",
        "ansi": "\033[33m",
    },
    "2": {
        "int": 2,
        "color": "Red",
        "description": "Sad \U0001f61e",
        "ansi": "\033[91m",
    },
    "1": {
        "int": 1,
        "color": "Brown",
        "description": "Miserable \U0001f622",
        "ansi": "\033[31m",
    },
}

QUOTES = {
    1: "The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
    2: "You may encounter many defeats, but you must not be defeated. In fact, it may be necessary to encounter the defeats, so you can know who you are, what you can rise from, how you can still come out of it. - Maya Angelou",
    3: "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    4: "Although the world is full of suffering, it is also full of the overcoming of it. - Helen Keller",
    5: "You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne",
    6: "You can't start the next chapter of your life if you keep re-reading the last one. - Unknown",
    7: "And once the storm is over, you won't remember how you made it through, how you managed to survive. You won't even be sure whether the storm is really over. But one thing is certain. When you come out of the storm, you won't be the same person who walked in. That’s what this storm’s all about. - Haruki Murakami",
    8: "Rock bottom became the solid foundation on which I rebuilt my life. - J.K. Rowling",
    9: "There is no royal road to anything, one thing at a time, all things in succession. That which grows fast, withers as rapidly. That which grows slowly, endures. - Josiah Gilbert Holland",
    10: "Every day is an adventure. Dare it. Every day is a danger. Face it. Every day is a love story. Read it. Every day is a tragedy. Endure it. Every day is a battle. Fight it. Every day is a joy. Celebrate it. - Unknown",
    11: "Stars form from the destruction of galaxies. - Needa Rehman",
    12: "We're all stories in the end. Just make it a good one, eh? - Eleventh Doctor from Doctor Who",
    13: "You can never cross the ocean unless you lose sight of the shore. - Anonymous",
    14: "The journey of a thousand miles begins with one step. - Lao Tzu",
    15: "When you wake up, you get to make a choice. You can either be like everyone else, or you can be different. - Thirteenth Doctor from Doctor Who",
    16: "It always seems impossible until it's done. - Nelson Mandela",
    17: "Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain. - Unknown",
    18: "Believe you can and you're halfway there. - Theodore Roosevelt",
    19: "The only way to do great work is to love what you do. - Steve Jobs",
    20: "You miss 100% of the shots you don't take. - Wayne Gretzky",
    21: "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    22: "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    23: "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    24: "In the end, we will remember not the words of our enemies, but the silence of our friends. - Martin Luther King Jr.",
    25: "It is never too late to be what you might have been. - George Eliot",
    26: "You must be the change you wish to see in the world. - Mahatma Gandhi",
    27: "The best way to predict the future is to create it. - Abraham Lincoln",
    28: "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    29: "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    30: "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    31: "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    32: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it. - Jordan Belfort",
    33: "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    34: "It does not matter how slowly you go as long as you do not stop. - Confucius",
    35: "Act as if what you do makes a difference. It does. - William James",
    36: "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    37: "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    38: "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    39: "A person who never made a mistake never tried anything new. - Albert Einstein",
    40: "You can't go back and change the beginning, but you can start where you are and change the ending. - C.S. Lewis",
    41: "The best revenge is massive success. - Frank Sinatra",
    42: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    43: "If you’re going through hell, keep going. - Winston Churchill",
    44: "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    45: "Do what you can with all you have, wherever you are. - Theodore Roosevelt",
    46: "The harder you work for something, the greater you’ll feel when you achieve it. - Unknown",
    47: "Dream big and dare to fail. - Norman Vaughan",
    48: "Success is not in what you have, but who you are. - Bo Bennett",
    49: "Hard work beats talent when talent doesn’t work hard. - Tim Notke",
    50: "Opportunities don't happen, you create them. - Chris Grosser",
    51: "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    52: "Don't wait for opportunity. Create it. - Unknown",
    53: "The secret of getting ahead is getting started. - Mark Twain",
    54: "If you can dream it, you can do it. - Walt Disney",
    55: "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    56: "The key to success is to focus on goals, not obstacles. - Unknown",
    57: "Do one thing every day that scares you. - Eleanor Roosevelt",
    58: "Everything has beauty, but not everyone can see it. - Confucius",
    59: "Success doesn’t just find you. You have to go out and get it. - Unknown",
    60: "Dream it. Wish it. Do it. - Unknown",
    61: "The way to get started is to quit talking and begin doing. - Walt Disney",
    62: "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    63: "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    64: "To live a creative life, we must lose our fear of being wrong. - Joseph Chilton Pearce",
    65: "The secret to getting ahead is getting started. - Mark Twain",
    66: "Nothing is impossible, the word itself says 'I'm possible'! - Audrey Hepburn",
    67: "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact. - William James",
    68: "What we think, we become. - Buddha",
    69: "The only way to do great work is to love what you do. - Steve Jobs",
    70: "In the middle of difficulty lies opportunity. - Albert Einstein",
    71: "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    72: "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
    73: "Success is not in what you have, but who you are. - Bo Bennett",
    74: "Action is the foundational key to all success. - Pablo Picasso",
    75: "The best way to predict the future is to create it. - Abraham Lincoln",
    76: "It does not matter how slowly you go as long as you do not stop. - Confucius",
    77: "Our lives begin to end the day we become silent about things that matter. - Martin Luther King Jr.",
    78: "Believe you can and you're halfway there. - Theodore Roosevelt",
    79: "Nothing will work unless you do. - Maya Angelou",
    80: "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    81: "The harder you work for something, the greater you’ll feel when you achieve it. - Unknown",
    82: "If you can dream it, you can do it. - Walt Disney",
    83: "The secret of getting ahead is getting started. - Mark Twain",
    84: "Success is not in what you have, but who you are. - Bo Bennett",
    85: "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    86: "The best revenge is massive success. - Frank Sinatra",
    87: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    88: "If you’re going through hell, keep going. - Winston Churchill",
    89: "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    90: "Do what you can with all you have, wherever you are. - Theodore Roosevelt",
    91: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    92: "Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain. - Unknown",
    93: "Success doesn’t just find you. You have to go out and get it. - Unknown",
    94: "Dream big and dare to fail. - Norman Vaughan",
    95: "The best way to predict the future is to create it. - Abraham Lincoln",
    96: "Success is not in what you have, but who you are. - Bo Bennett",
    97: "Hard work beats talent when talent doesn’t work hard. - Tim Notke",
    98: "Opportunities don't happen, you create them. - Chris Grosser",
    99: "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    100: "Don't wait for opportunity. Create it. - Unknown",
    101: "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    102: "Everything you can imagine is real. - Pablo Picasso",
    103: "The journey of a thousand miles begins with one step. - Lao Tzu",
    104: "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    105: "It does not matter how slowly you go as long as you do not stop. - Confucius",
    106: "The harder you work for something, the greater you’ll feel when you achieve it. - Unknown",
    107: "Don’t let yesterday take up too much of today. - Will Rogers",
    108: "If you can dream it, you can do it. - Walt Disney",
    109: "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    110: "The best way to predict the future is to create it. - Abraham Lincoln",
    111: "It always seems impossible until it's done. - Nelson Mandela",
    112: "A person who never made a mistake never tried anything new. - Albert Einstein",
    113: "Success doesn’t just find you. You have to go out and get it. - Unknown",
    114: "You can't go back and change the beginning, but you can start where you are and change the ending. - C.S. Lewis",
    115: "Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain. - Unknown",
    116: "Believe you can and you're halfway there. - Theodore Roosevelt",
    117: "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    118: "Be yourself; everyone else is already taken. - Oscar Wilde",
    119: "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    120: "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    121: "What we think, we become. - Buddha",
    122: "The secret to getting ahead is getting started. - Mark Twain",
    123: "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    124: "Life is what happens when you’re busy making other plans. - John Lennon",
    125: "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    126: "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    127: "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    128: "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    129: "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    130: "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    131: "The way to get started is to quit talking and begin doing. - Walt Disney",
    132: "Do one thing every day that scares you. - Eleanor Roosevelt",
    133: "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    134: "Success is the ability to go from one failure to another with no loss of enthusiasm. - Winston Churchill",
    135: "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    136: "The only way to do great work is to love what you do. - Steve Jobs",
    137: "Opportunities don't happen, you create them. - Chris Grosser",
    138: "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    139: "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
    140: "Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain. - Unknown",
    141: "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    142: "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
    143: "Everything has beauty, but not everyone can see it. - Confucius",
    144: "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    145: "You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne",
    146: "Our lives begin to end the day we become silent about things that matter. - Martin Luther King Jr.",
    147: "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact. - William James",
    148: "If you can dream it, you can do it. - Walt Disney",
    149: "Act as if what you do makes a difference. It does. - William James",
    150: "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    151: "Don’t let the noise of others’ opinions drown out your own inner voice. - Steve Jobs",
    152: "Your time is limited, don’t waste it living someone else’s life. - Steve Jobs",
    153: "I attribute my success to this: I never gave or took any excuse. - Florence Nightingale",
    154: "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    155: "You must be the change you wish to see in the world. - Mahatma Gandhi",
    156: "Everything you can imagine is real. - Pablo Picasso",
    157: "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    158: "Don't let yesterday take up too much of today. - Will Rogers",
    159: "The best revenge is massive success. - Frank Sinatra",
    160: "We may encounter many defeats, but we must not be defeated. - Maya Angelou",
    161: "The way to get started is to quit talking and begin doing. - Walt Disney",
    162: "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    163: "In the end, it's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
    164: "Life is what happens when you're busy making other plans. - John Lennon",
}
